#!/usr/bin/env python
import roslib; roslib.load_manifest('teleop_twist_keyboard')
import rospy

from geometry_msgs.msg import Twist
from std_msgs.msg import Empty

import sys, select, termios, tty


safeActions = {

	'moveBackward',
	'moveLeft',
	'moveRight',
	'moveUp',
	'moveDown',
	'turnLeft',
	'turnRight',
	'stop,
	'takeOff',
	'land',
	'emergencyStop',
	'increaseMaxSpeed',
	'decreaseMaxSpeed',
	'increaseLinearSpeed',
	'decreaseLinearSpeed',
	'increaseAngularSpeed',
	'decreaseAngularSpeed',
}
